# Generated by Django 4.2.3 on 2023-08-04 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='pay_sum',
            field=models.IntegerField(default=0, verbose_name='сумма платежа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pay',
            name='course_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Course.course'),
        ),
    ]
