version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: my_password
      PGDATA: /var/lib/postgresql/data/pgdata
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
  celery:
    build:
      context: .
      #dockerfile: docker/celery/Dockerfile
    depends_on:
      - app
      - redis