# Generated by Django 4.2.3 on 2023-07-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_name",
                    models.CharField(max_length=100, verbose_name="название курса"),
                ),
                (
                    "course_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="описание курса"
                    ),
                ),
                (
                    "course_preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="course/",
                        verbose_name="изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "курс",
                "verbose_name_plural": "курсы",
            },
        ),
    ]
