# Generated by Django 4.2.3 on 2023-08-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Course", "0002_course_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.FloatField(default=1000.0, verbose_name="Цена USD"),
        ),
    ]
